name: CI

on:
  push:
    branches: [ "dev/hw5" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Create directory
      run: mkdir ${{github.workspace}}/build
    - name: Create cmake
      working-directory: ${{github.workspace}}/build
      run: |
        cmake ..
        cmake --build .  
    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C
  valgrind:
    needs: Test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: create folder
      run: mkdir ${{github.workspace}}/build
    - name: Create cmake
      working-directory: ${{github.workspace}}/build
      run: |
        cmake .. 
        cmake --build ${{github.workspace}}/build
    - name: Valgrind install
      run: sudo apt-get install valgrind
      
    - name: Valgrind check
      working-directory: ${{github.workspace}}/build
      run: valgrind --tool=memcheck --leak-check=yes --error-exitcode=1 ./ci_project 